### ISSUE TITLE
Invoice page coloring re-design

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1405]
**Is your feature request related to a problem? Please describe.**
Our invoice page should be re-freshed a bit. With new website design coming and future server coloring changes, this is the first step towards new, cleaner look.

**Describe the solution you'd like**
![Screenshot 2020-03-22 at 09 57 40](https://user-images.githubusercontent.com/36959754/77246030-99e81380-6c23-11ea-9d15-bd729b601c58.png)

Designs by @dstruct on mattermost.
@rockstardev  [CSS available here.](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=766%3A123)
**Additional context**
These mockups may include some positioning changes, note that in this issue we're tackling just basic css coloring and minor styling that won't break the theme for [those using custom themes.](https://github.com/btcpayserver/btcpayserver-doc/blob/master/Theme.md#checkout-page-themes)
### Todo
- [ ] Make coloring changes to the invoice
- [ ] See if we can center the logo without breaking things for people using custom themes
- [ ] Test against a custom theme to make sure nothing breaks

**Comment by Eskyee** [comment]
Excellent 📡

**Comment by Eskyee** [comment]
I personally prefer B  pav

**Comment by bolatovumar** [comment]
@pavlenex @rockstardev I can work on this if you don't mind. I imagine rockstar is quite busy these days.

**Comment by pavlenex** [comment]
@bolatovumar Already agreed that Rockstar is taking this one over, since we discussed some breaking changes that may happen for users using custom themes. 

If you can dm me on Mattermost we can discuss find something you can tackle for sure  also may be good that I introduce you with the new process of tackling issues we're taking, should be easier for you and other people to understand the bigger picture 😃

**Comment by NicolasDorier** [comment]
so sexy I can't wait

**Comment by dStruct** [comment]
Someone @‘d me but I have nothing to do with this project.

**Comment by pavlenex** [comment]
#1423
