### ISSUE TITLE
[Tracker] Improve recovery seed backup page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#4304]
This is a tracker issue for improving the view where user creates a wallet and recovery seed is shown to them. This one is potentially for 1.8.0 and later. 

Below is a list of tasks that we've discussed on Mattermost:

- [x] Display seed in a standard two-column way, the way in which we display seed currently is confusing #4793
- [ ] Iron out the copy and assure it's concise and clear
- [ ] Create a seed validation page, inspiration for design can be found in the bitcoin design guide [here](https://bitcoin.design/guide/daily-spending-wallet/backup-and-recovery/manual-backup/#how-to-display-a-recovery-phrase)
![Screenshot 2022-11-18 at 10 56 50](https://user-images.githubusercontent.com/36959754/202674924-68f96c25-b819-4afe-9323-e5c479a7ca5f.png)

**Comment by daviogg** [comment]
I would love to work on this issue 👍

**Comment by TChukwuleta** [comment]
Hello team, I would love to work on this issue.

**Comment by dennisreimann** [comment]
@dstrukt can confirm, but I think these are the [latest mocks](https://www.figma.com/file/lE9dYRMqoABkJrn0VdXTE4/App?node-id=2253%3A77350&t=InneebFaRUx5C1VT-4):

![grafik](https://user-images.githubusercontent.com/886/224340493-c599288f-888b-409f-a99f-50403a6622a6.png)

![grafik](https://user-images.githubusercontent.com/886/224340542-86490003-0925-4121-81f3-3d1c08fab25d.png)

![grafik](https://user-images.githubusercontent.com/886/224340660-66cdff6f-2bff-4f78-a597-87175df94c1e.png)

**Comment by TChukwuleta** [comment]
Hello @dennisreimann, just to confirm, these images are in order according to the flow yea?

**Comment by dennisreimann** [comment]
Yes, we present the seed words once a new wallet is created within BTCPay Server — you can get to that via the Wallet Setup and choosing the create option.

Right now we only have the first screen of those mocks, which we'd need to alter the order of word on to make it more intuitive. Currently we display them in column order and it is supposed to go from left to right in rows.

The second and third mock shows the confirmation screen, which should be interactive and have success and error state as shown in the third image.

Let me know in case you have questions or need help with the implementation — you can also reach out on [our Mattermost chat](https://chat.btcpayserver.org). Have fun!

**Comment by TChukwuleta** [comment]
Hello @dennisreimann, I am currently working on the screen and logic for the second and third pages to keep you updated. 
I am not a big fan of front-end, so I am a bit slow. But I am done with the first-page update. If you like, I can raise a PR.

**Comment by dennisreimann** [comment]
Sure! Also let me know if I can assist or in case you need guidance. I recommended this one, because the one you wanted to grab initially was also frontend-related. 

If you don't like it, we can also see if there's a better fit for something you would enjoy to work on. Let me know.

**Comment by NicolasDorier** [comment]
Please do not force users to confirm their mnemonic

**Comment by pavlenex** [comment]
@NicolasDorier Why not? This is a [common](https://bitcoin.design/guide/daily-spending-wallet/backup-and-recovery/manual-backup/#confirming-a-backup) practice.

**Comment by NicolasDorier** [comment]
The fact it is a common practice doesn't mean it's not pain in the ass. BTCPay isn't my mother, if I don't want to confirm, I hate being forced to.

**Comment by dstrukt** [comment]
I agree it can be quite annoying, but also understand why it's done, and am a bit on the fence, as I try to look at it as a way of double checking that I recorded the information correctly.

Would a reasonable compromise be something more simple/easy than the proposed? Or would you just like to drop these feature all together?

@NicolasDorier
