### ISSUE TITLE
[Checkout V2] Feedback & Iteration

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/btcpayserver#4364]
Will be updating this list, but will coordinate with @dennisreimann to make sure we're addressing everything.

- [x] Round all the `full-width` buttons
- [x] Add `back to store` button back to `Expired` view
- [x] Option: [Confetti](https://www.kirilv.com/canvas-confetti/#realistic) for successful payments - #4727 
- [x] Option: Display amount in sats when using BIP21 - #4730 

### NFC Support
- [x] https://github.com/btcpayserver/btcpayserver/issues/4443

### Copy Address CTA
- [x] https://github.com/btcpayserver/btcpayserver/issues/4442

### Custom CSS
- [x] Custom CSS option: #4459

### Unit Displays & Copy Functionality

- [x] Improve the BTC => USD conversion key/pair label `$16,543.45 (USD)` => `16,543.45 USD` #4736
- [x] Improve USD display `$8,000.00 (USD)` => `8,000.00 USD` #4736
- [ ] Should copying the fiat amount just copy the number `16,543.45`, imo, yes ... or everything, e.g. we currently copy this `$16,543.45 (USD)`  — can be done in  #4734 once #4736 is done

### Paid Invoice
- [x] Add copy icons to `Paid Invoice` view, and any other views #4734
- [x] Remove gap, if possible #4473
<img width="399" alt="Screen Shot 2022-12-05 at 4 24 55 PM" src="https://user-images.githubusercontent.com/6250771/205775761-04113418-29b4-4c7f-a563-3193153b0207.png">

### Copy Suggestions & Improvements

- [x] `Return to {Store} if you like to resubmit a payment.` => `Return to {Store} if you would like to resubmit a payment.`  #4734

### Translation

- [x] #4444
- [x] Add Language selector button #4723
