### ISSUE TITLE
POS Product Cart view - make it consistent with our design guidelines and dstruktify it!

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5109]
Our POS Cart view seemed to be used quite a lot, however the design/styling of it looks quite outdated compared to our design system . This is a tracker issue that will try to log all the improvements we need to make, but those improvements will be posted here most likely  next week once we determine course of action.

Bear in mind that there will be category/group changes coming in that we should consider. #5078 
```[tasklist]
### Tasks
- [x] Come up with design @dstrukt
- [x] Implement proposed design
- [x] Ensure we only touch on cosmetic side of things, but also think if we'd like to improve the checkout flow for the next major release
```

**Comment by dstrukt** [comment]
I love that I've been given an adverb to describe my pixel pushing!

It's not kukksification, but it's honest work.

**Comment by dennisreimann** [comment]
Should incorporate #5130 and the changes made in #5088
