### ISSUE TITLE
Move features that aren't considered "core" into plugins

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#5588]
Going into 2024, one of the things we discussed is that core-codebase needs to be simpler and accessible to new contributors. One of our major goals in 2024 is to move redundant code into plugins and ensure core is stable, secure and easy enough. 

This issue serves as a tracker, and it's up for discussion on what else can be added.

One thing that was discussed is that we should start moving certain things into external codebases/plugins. This also includes altcoins.

```[tasklist]
### Tasks
- [ ] Move POS to plugin
- [ ] Move CF to plugin
- [ ] Move Shopify to plugin
- [ ] Move lightning addresss to plugin
- [ ] Move pay button to plugin
- [ ] Move all Altcoins to plugins
```
