### ISSUE TITLE
Withdrawal fund's

### ISSUE THREAD

**Issue by Jpspartan** [btcpayserver/btcpayserver#5664]
[ASICProCertificate.pdf](https://github.com/btcpayserver/btcpayserver/files/13947563/ASICProCertificate.pdf)
[Uploading banking-code-of-practice.pdf…]()
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/5663

<div type='discussions-op-text'>

<sup>Originally posted by **Jpspartan** January 16, 2024</sup>
Can I have some moral support for the Bitcoin mining funds funds please?</div>
```[tasklist]
### Tasks
- [ ] https://github.com/btcpayserver/btcpayserver/pull/5627
```

```[tasklist]
### Tasks
- [ ] https://github.com/btcpayserver/btcpayserver/pull/5647
- [ ] https://github.com/btcpayserver/btcpayserver/pull/5662
```
