### ISSUE TITLE
Removal of some DB column that aren't needed

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#5903]
```[tasklist]
### Tasks
- [x] InvoiceEvents contains an unused 10 bytes UniqueId (Cleanup data from the InvoiceEvents table #5904), which consume a lot of space.
- [x] Cleanup AddressesInvoices table (Cleanup AddressesInvoices table #5905)
- [x] Remove CustomerEmail, ItemCode, OrderId, Archived? from Invoices table
```

**Comment by pavlenex** [comment]
@NicolasDorier did you finish this one? Or is that still something remaining, if it's finished let's close it? If there's more we can add it to 2.1.0?
